Repository mikeriepe/amplifytasselapp, pull requests merged in 2023-11, with the labels that each got.

#50 Social page
  amplifytassel/src/app/App.js
  amplifytassel/src/app/components/NavBarLoggedIn.js
  amplifytassel/src/app/components/SocialFriendRequests.js
  amplifytassel/src/app/components/SocialFriends.js
  amplifytassel/src/app/components/SocialUsers.js
  amplifytassel/src/app/components/ThemedButton.js
  amplifytassel/src/app/pages/Social.js
Labels: enhancement

#51 duplicate emails generate popup
  amplifytassel/.eslintignore
  amplifytassel/.gitignore
  amplifytassel/src/app/pages/Signup.js
  amplifytassel/src/models/index.d.ts
  amplifytassel/src/models/index.js
  amplifytassel/src/models/schema.js
  amplifytassel/src/ui-components/KeywordCreateForm.jsx
  amplifytassel/src/ui-components/KeywordUpdateForm.jsx
  amplifytassel/src/ui-components/MajorCreateForm.jsx
  amplifytassel/src/ui-components/NewForm1.jsx
  amplifytassel/src/ui-components/NewForm3.jsx
  amplifytassel/src/ui-components/NoteCreateForm.jsx
  amplifytassel/src/ui-components/NoteUpdateForm.jsx
  amplifytassel/src/ui-components/OrganizationCreateForm.jsx
  amplifytassel/src/ui-components/OrganizationUpdateForm.jsx
  amplifytassel/src/ui-components/ProfileCreateForm.jsx
  amplifytassel/src/ui-components/ProfileUpdateForm.jsx
  amplifytassel/src/ui-components/index.js
  amplifytassel/src/ui-components/utils.js
Labels: bug

#52 Once logged in the user gets rerouted to dashboard
  amplifytassel/src/app/pages/Landing.js
Labels: bug

#54 Added Keep me logged in check box functionality
  amplifytassel/src/app/App.js
  amplifytassel/src/app/pages/Login.js
Labels: enhancement

#63 filtering out and deleting friends
  amplifytassel/src/app/components/SocialFriends.js
  amplifytassel/src/app/components/SocialUsers.js
Labels: enhancement

#64 New Models and naming convention for Friend Requests
  amplifytassel/amplify/backend/api/amplifytassel/schema.graphql
  amplifytassel/src/app/components/SocialFriendRequests.js
  amplifytassel/src/app/components/SocialUsers.js
  amplifytassel/src/models/index.d.ts
  amplifytassel/src/models/index.js
  amplifytassel/src/models/schema.js
  amplifytassel/src/ui-components/ChatRoomCreateForm.d.ts
  amplifytassel/src/ui-components/ChatRoomCreateForm.jsx
  amplifytassel/src/ui-components/ChatRoomUpdateForm.d.ts
  amplifytassel/src/ui-components/ChatRoomUpdateForm.jsx
  amplifytassel/src/ui-components/index.js
Labels: enhancement

#65 Master check box Functionality added
  amplifytassel/.eslintignore
  amplifytassel/src/app/components/ApprovalAccounts.js
  amplifytassel/src/app/components/SocialFriendRequests.js
  amplifytassel/src/app/components/SocialFriends.js
  amplifytassel/src/app/components/SocialUsers.js
Labels: bug, enhancement

#66 fixed naming
  amplifytassel/src/app/components/SocialFriendRequests.js
  amplifytassel/src/app/components/SocialFriends.js
Labels: enhancement

#67 Display chats in message tab
  amplifytassel/src/app/components/SocialIncomingRequests.js
  amplifytassel/src/app/components/SocialMessages.js
  amplifytassel/src/app/components/SocialOutgoingRequests.js
  amplifytassel/src/app/pages/Social.js
Labels: enhancement

#69 Fixed master checkbox on opportunities tab and approve/deny loading bug
  amplifytassel/src/app/components/ApprovalOpportunities.js
Labels: bug

#79 Recent Message Column
  amplifytassel/src/app/components/SocialMessages.js
Labels: enhancement
